
/* 

React dom elements
React dom events
e = event
preventDefault - prevent full page refresh

INFO: JSX support stings, numbers and arrays by default. It doesn't support objects and ignore booleans, null or undefined by not rendering them. We can render JSX inside JSX. Adding key to elements hepls JSX to optimize renderind.

*/


const app = {
    title: 'Indecision App',
    subtitle: 'Put your life in the hands of a computer',
    options: []
}

const onFormSubmit = (e) => {
    e.preventDefault();

    // get the value that user type
    const option = e.target.elements.option.value;

    //check if there is any option
    if (option) {
        app.options.push(option);

        //clear the input
        e.target.elements.option.value = '';

        //render the new data
        renderApp();
    }
}

const removeOptions = () => {
    app.options = [];
    renderApp();
}

const onMakeDecision = () => {

    // ~~ = Math.floor()
    const randomNum = ~~(Math.random() * app.options.length);

    // get the item form the array at the position generated by the randomNum
    const selectedOption = app.options[randomNum];

    alert(selectedOption);
}

const renderApp = () => {
    const template = (
        <div>
            <h1>{app.title}</h1>

            {app.subtitle && <p>{app.subtitle}</p>}

            <p>{(app.options.length > 0) ? 'Here are your options:' : 'You have no options.'}</p>

            <ul>
                {
                    app.options.map((option, index) => <li key={index+1}>{option}</li>)
                }
            </ul>

            <p><button disabled={app.options.length === 0} onClick={onMakeDecision}>What should I do?</button></p>

            <p><button onClick={removeOptions}>Remove all options</button></p>

            <form onSubmit={onFormSubmit}>
                <input type="text" name="option"/>
                <button>Add option</button>
            </form>

        </div>
    );

    ReactDOM.render(template, appRoute);
}

const appRoute = document.getElementById('appRoute');

renderApp();


